### ISSUE TITLE
OS Error when more than one machine is connected.

### ISSUE THREAD

**Issue by Revel8804** [odwdinc/Python-SimConnect#38]
When I only have one machine connected all is well. 

When i attempt to watch on a second machine like my phone. then the server crashes.

`OSError: [WinError -1073741648] Windows Error 0xc00000b0
192.168.1.31 - - [21/Sep/2020 16:42:20] "←[35m←[1mGET /ui HTTP/1.1←[0m" 500 -
Traceback (most recent call last):
  File "C:\Python38\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python38\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python38\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Tools\MSFS2020_Utilities\fs2020cockpit\glass_server.py", line 306, in output_ui_variables
    fuel_percentage = (aq.get("FUEL_TOTAL_QUANTITY") / aq.get("FUEL_TOTAL_CAPACITY")) * 100
  File "C:\Users\kenny\AppData\Roaming\Python\Python38\site-packages\SimConnect\RequestList.py", line 179, in get
    return request.value
  File "C:\Users\kenny\AppData\Roaming\Python\Python38\site-packages\SimConnect\RequestList.py", line 17, in value
    self.sm.run()
  File "C:\Users\kenny\AppData\Roaming\Python\Python38\site-packages\SimConnect\SimConnect.py", line 171, in run
    self.dll.CallDispatch(self.hSimConnect, self.my_dispatch_proc_rd, None)
  File "_ctypes/callproc.c", line 948, in GetResult

OSError: [WinError -1073741648] Windows Error 0xc00000b0`

**Comment by odwdinc** [comment]
Nice find, had to get 3 derives to see the error,
The last push should fix, pip is giving troubles though..

**Comment by odwdinc** [comment]
fixed in SimConnect 0.4.11

**Comment by Revel8804** [comment]
thank you sir. the program is amazing!
