### ISSUE TITLE
Issue compiling using pyinstaller

### ISSUE THREAD

**Issue by hankhank10** [odwdinc/Python-SimConnect#79]
I am trying to compile a script which uses this library for Windows using pyinstaller. The script in question is here: https://github.com/hankhank10/findmyplane-client

I have tried both calling the SimConnect library via a pip install and putting the source code in a SimConnect directory.

In both instances I get the following error when I run my script.

Any advice?

Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 167, in __init__
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\Shadow\AppData\Local\Temp\_MEI40562\SimConnect\SimConnect.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "client.py", line 114, in <module>
  File "SimConnect\SimConnect.py", line 125, in __init__
  File "SimConnect\Attributes.py", line 18, in __init__
  File "ctypes\__init__.py", line 452, in LoadLibrary
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 169, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\Shadow\\AppData\\Local\\Temp\\_MEI40562\\SimConnect\\SimConnect.dll'. Most probably this dynlib/dll was not found when the application was frozen.
[14956] Failed to execute script client

**Comment by hankhank10** [comment]
I fixed this myself.

For future reference:

pyinstaller -F --add-binary SimConnect.dll;. client.py

**Comment by zeykafx** [comment]
Hi, for some reason if I didn't surround the SimConnect.dll;. by quotation marks it wouldn't compile, I ended up with 
`pyinstaller index.py  -F --add-binary "SimConnect.dll;."`
